[Definition]
# Ban IPs generating 4xx/5xx on Traefik access logs (JSON format)
failregex = ^.*"ClientAddr":"<HOST>:.*"RequestPath":".*"DownstreamStatus":(4[0-9]{2}|5[0-9]{2}).*$
ignoreregex =
datepattern = %%Y-%%m-%%dT%%H:%%M:%%S
